### ISSUE TITLE
Cannot read property 'data' of null

### ISSUE THREAD

**Issue by yeya** [danielgindi/js-i18n#1]
[Line 486](https://github.com/danielgindi/js-i18n/blob/fc15d2122f91b8abf0e57aa477daf0fed3efd2d3/i18n.js#L486) throw `TypeError: Cannot read property 'data' of null` in case `useOriginal` not exist.

Because [line 483](https://github.com/danielgindi/js-i18n/blob/fc15d2122f91b8abf0e57aa477daf0fed3efd2d3/i18n.js#L483)

**Comment by danielgindi** [comment]
That is only if you don't select a default locale, so there's nothing active
